// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "c3019dfe-cfdf-4e23-9d65-d711dba8d9e1";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password


String calidadAire;
CloudTemperatureSensor temperatura;
CloudRelativeHumidity humedad;
bool calidadAireBool;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(calidadAire, READ, 5 * SECONDS, NULL);
  ArduinoCloud.addProperty(temperatura, READ, 5 * SECONDS, NULL);
  ArduinoCloud.addProperty(humedad, READ, 5 * SECONDS, NULL);
  ArduinoCloud.addProperty(calidadAireBool, READ, 5 * SECONDS, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
